ACME: src.utils.backup.custom_logger Namespace Reference
src.utils.backup.custom_logger Namespace Reference
Classes
class CallStackFormatter
class LogManager
Functions
Union[logging.Formatter, CallStackFormatter] _build_default_formatter (int level, str child_name, int colr_id, formatter_class=logging.Formatter)
logging.Handler _configure_handler (logging.Formatter formatter, int level, handler_delegate, dict handler_kwargs)
logging.Logger _logger_setup (logging.Logger logger, str header_label, Formatter formatter=None, int level=logging.INFO, int level_normalized=logging.INFO, handler_delegate=logging.StreamHandler, **handler_kwargs)
logging.Logger get_logger (str root_name, str child_name=None, str header_label=None, Union[Formatter, str] formatter=None, Union[int, str] level=None, dict logger_registration_dict=None, handler_delegate=logging.StreamHandler, bool do_file_output=False, **handler_kwargs)
def get_logging_file_target (str or int level, str or Path fname, bool just_first=True)
Variables
bool DEBUGGING = True
level
dictionary LOGGER_COLLECTION = {}
string ESC_SEQ = "\033["
string HIGH_PRI_LOGGER_HEADER_COLOR_PREFIX = ESC_SEQ + "1;4;7;{}m"
string LOW_PRI_LOGGER_HEADER_COLOR_PREFIX = ESC_SEQ + "1;4;{}m"
string LOGGER_MSG_COLOR = ESC_SEQ + "1;{}m"
string LOGGER_MSG_COLOR_INVERTED = ESC_SEQ + "1;7;{}m"
int NOTSET_ID = 90
int DBG_ID = 35
int INFO_ID = 32
int WARN_ID = 36
int ERR_ID = 95
int CRIT_ID = 91
string RESET = ESC_SEQ + "0m"
dictionary color_formatting_dict
dictionary log_id_map
dictionary LEVELS_STR2INT
dictionary LEVELS_INT2STR = {v:k for k,v in LEVELS_STR2INT.items()}
dictionary logging_target_files
logging.Logger _logger_setup_internal_warning_logger = get_logger(__name__, "logger_setup_warning", level="WARNING")
string project_root = "EmailClassifier"
logging.Logger import_warnings_logger = get_logger(project_root,__name__+": import warnings",level="WARNING").warning
logging.Logger root_info_logger = get_logger(project_root,__name__+": INFO log",level="INFO")
Detailed Description
This is a general purpose utility file for setting up logger output that's good for
quick visual scans of a program's diagnostic data.
Function Documentation
_build_default_formatter()
Union[logging.Formatter, CallStackFormatter] src.utils.backup.custom_logger._build_default_formatter (int level, str child_name, int colr_id, formatter_class = logging.Formatter) private
Definition at line 219 of file custom_logger.py.
Referenced by src.utils.backup.custom_logger._logger_setup().
_configure_handler()
logging.Handler src.utils.backup.custom_logger._configure_handler (logging.Formatter formatter, int level, handler_delegate, dict handler_kwargs) private
Definition at line 252 of file custom_logger.py.
Referenced by src.utils.backup.custom_logger._logger_setup().
_logger_setup()
logging.Logger src.utils.backup.custom_logger._logger_setup (logging.Logger logger, str header_label, Formatter formatter = None, int level = logging.INFO, int level_normalized = logging.INFO, handler_delegate = logging.StreamHandler, ** handler_kwargs) private
A convenience function for creating well named loggers with optional custom formatter.
This function will implement an already defined formatter for you if the formatter param is
None. For an example of a good general use logger see the example code at the bottom of this
file.
SPECIAL NOTE:
    Although this function's signature allows the caller to pass virtually any logging.Handler
    subclass into the handler_delegate parameter, I've only tested this functionality against
    the logging.StreamHandler class. If you wish to use it for others you will likely encounter
    bugs. But if you are up to the task it seems like it could potentially be a helpful tool for
    allowing the instantiation of a wide array of utility loggers under a single interface.
:param header_label:
:param logger: an initialized logger object that needs to have its formatter and optinoal handlers set.
:param child_name:  The auxiliary logger you wish to create to handle some specific task. The
                    logger which maps to this child will set its level, handlers, and formatters
                    according to your inputs, allowing you to specify many different loggers to
                    manage _data output in a form that suites you.
:type child_name:   A string
:param formatter:   An optional parameter that specifies the manner in which you wish to format
                    the available logging-event-_data as well as how you wish to present the
                    message _data for your log events. The default formatter will take one of
                    two styles, based the given `level`.
                    For level==logging.INFO (20) and bellow:
                        log messages will be presented in two parts.
                            * First, a header line that's formatted to be bold, and underlined,
                              that gives the time-stamp for when the log was submitted, the
                              child_name, the model and function and line number from which the
                              log-message was originated
                            * Followed by an indented new-line where the log-message will be
                              be printed. The message
                    For level==logging.INFO+1 (21) and above:
                        log messages will be presented in two parts.
                            * First, a header line that's formatted to be bold, and underlined,
                              that gives the time-stamp for when the log was submitted, the
                              child_name, the model and function and line number from which the
                              log-message was originated
                            * Followed, on the same line as the header, the log-message. This
                              distinction, as opposed to the indented new-line in lower level
                              messaged, is done because it is often the case the when higher
                              level messages occur, there are very many of them. Forcing each
                              one to then be a multi-line message actually makes it much harder
                              to visually parse.
                            * Special note: In order to aid in automated parsing of these
                              log-messages, the header details and log message will be seperated
                              by the following character key:
                                    `::>`
:type formatter:    an instance of logging.Formatter
:param handler_delegate: An optional parameter that Specifies the type of handler you want to
                         associate to the logger instance that's mapped to the
                         root_name.child_name you've passed in. The handler will be set up
                         inside of this function, this parameter simply allows you to indicate
                         the way you wish to have your output handled.
                         (E.G. to std_out, std_err, or some file output stream)
:type handler_delegate:  This should be a delegate function of your desired handler's
                         constructor, DEFAULT=logging.StreamHandler
:param level:   Specifies the desired logging level of the resulting logger.
                DEFAULT=logging.DEBUG
:type level:    An int, must be in the range of [0,0xffffffff]
:type handler_kwargs: Any additional keywords that should be passed into the construction of the
                      handler. These are necessary for the instantiation of handlers that will
                      output to anything other than sys.std_out, and sys.std_err.
:return:    a reference to the logger instance that's mapped to the input naming scheme of
            <root_name>.<child_name >
:rtype: logging.Logger
Definition at line 260 of file custom_logger.py.
References src.utils.backup.custom_logger._build_default_formatter(), and src.utils.backup.custom_logger._configure_handler().
Referenced by src.utils.backup.custom_logger.LogManager.__getattribute__(), and src.utils.backup.custom_logger.get_logger().
get_logger()
logging.Logger src.utils.backup.custom_logger.get_logger (str root_name, str child_name = None, str header_label = None, Union[Formatter,str] formatter = None, Union[int, str] level = None, dict logger_registration_dict = None, handler_delegate = logging.StreamHandler, bool do_file_output = False, ** handler_kwargs)
Definition at line 365 of file custom_logger.py.
References src.utils.backup.custom_logger._logger_setup(), and src.utils.backup.custom_logger._logger_setup_internal_warning_logger.
Referenced by src.utils.backup.custom_logger.LogManager.add_logger_as_field().
get_logging_file_target()
def src.utils.backup.custom_logger.get_logging_file_target (str or int level, str or Path fname, bool just_first = True)
Definition at line 485 of file custom_logger.py.
Variable Documentation
_logger_setup_internal_warning_logger
logging Logger src.utils.backup.custom_logger._logger_setup_internal_warning_logger = get_logger(__name__, "logger_setup_warning", level="WARNING") private
Definition at line 527 of file custom_logger.py.
Referenced by src.utils.backup.custom_logger.LogManager.add_logger_as_field(), and src.utils.backup.custom_logger.get_logger().
color_formatting_dict
dictionary src.utils.backup.custom_logger.color_formatting_dict
Definition at line 128 of file custom_logger.py.
CRIT_ID
int src.utils.backup.custom_logger.CRIT_ID = 91
Definition at line 126 of file custom_logger.py.
DBG_ID
int src.utils.backup.custom_logger.DBG_ID = 35
Definition at line 122 of file custom_logger.py.
DEBUGGING
int src.utils.backup.custom_logger.DEBUGGING = True
Definition at line 28 of file custom_logger.py.
ERR_ID
int src.utils.backup.custom_logger.ERR_ID = 95
Definition at line 125 of file custom_logger.py.
ESC_SEQ
string src.utils.backup.custom_logger.ESC_SEQ = "\033["
Definition at line 116 of file custom_logger.py.
HIGH_PRI_LOGGER_HEADER_COLOR_PREFIX
string src.utils.backup.custom_logger.HIGH_PRI_LOGGER_HEADER_COLOR_PREFIX = ESC_SEQ + "1;4;7;{}m"
Definition at line 117 of file custom_logger.py.
import_warnings_logger
logging.Logger src.utils.backup.custom_logger.import_warnings_logger = get_logger(project_root,__name__+": import warnings",level="WARNING").warning
Definition at line 534 of file custom_logger.py.
INFO_ID
int src.utils.backup.custom_logger.INFO_ID = 32
Definition at line 123 of file custom_logger.py.
level
src.utils.backup.custom_logger.level
Definition at line 70 of file custom_logger.py.
LEVELS_INT2STR
dictionary src.utils.backup.custom_logger.LEVELS_INT2STR = {v:k for k,v in LEVELS_STR2INT.items()}
Definition at line 172 of file custom_logger.py.
LEVELS_STR2INT
dictionary src.utils.backup.custom_logger.LEVELS_STR2INT
Initial value:
 =  {
     "NOTSET": logging.NOTSET,
     "DEBUG": logging.DEBUG,
     "INFO": logging.INFO,
     "WARNING": logging.WARNING,
     "ERROR": logging.ERROR,
     "CRITICAL": logging.CRITICAL}
Definition at line 164 of file custom_logger.py.
log_id_map
dictionary src.utils.backup.custom_logger.log_id_map
Initial value:
 =  {logging.ERROR: ERR_ID, logging.INFO: INFO_ID, logging.WARNING: WARN_ID,
               logging.DEBUG: DBG_ID, logging.NOTSET: NOTSET_ID,logging.CRITICAL:CRIT_ID}
Definition at line 162 of file custom_logger.py.
LOGGER_COLLECTION
dictionary src.utils.backup.custom_logger.LOGGER_COLLECTION = {}
Definition at line 72 of file custom_logger.py.
LOGGER_MSG_COLOR
string src.utils.backup.custom_logger.LOGGER_MSG_COLOR = ESC_SEQ + "1;{}m"
Definition at line 119 of file custom_logger.py.
LOGGER_MSG_COLOR_INVERTED
string src.utils.backup.custom_logger.LOGGER_MSG_COLOR_INVERTED = ESC_SEQ + "1;7;{}m"
Definition at line 120 of file custom_logger.py.
logging_target_files
dictionary src.utils.backup.custom_logger.logging_target_files
Initial value:
 =  {
     "DEBUG":"**/logging_output/debug/{}.log",
     "INFO":"**/logging_output/info/{}.log",
     "WARNING":"**/logging_output/warning/{}.log",
     "ERROR":"**/logging_output/error/{}.log",
     "CRITICAL":"**/logging_output/critical/{}.log",
     "LEVEL SPECIAL":{
         # for future cases where the code requires a clearly named custom implementation
         # place that implementation here and special handling can be developed for it.
     }
 }
Definition at line 174 of file custom_logger.py.
LOW_PRI_LOGGER_HEADER_COLOR_PREFIX
string src.utils.backup.custom_logger.LOW_PRI_LOGGER_HEADER_COLOR_PREFIX = ESC_SEQ + "1;4;{}m"
Definition at line 118 of file custom_logger.py.
NOTSET_ID
int src.utils.backup.custom_logger.NOTSET_ID = 90
Definition at line 121 of file custom_logger.py.
project_root
string src.utils.backup.custom_logger.project_root = "EmailClassifier"
Definition at line 533 of file custom_logger.py.
RESET
string src.utils.backup.custom_logger.RESET = ESC_SEQ + "0m"
Definition at line 127 of file custom_logger.py.
root_info_logger
logging.Logger src.utils.backup.custom_logger.root_info_logger = get_logger(project_root,__name__+": INFO log",level="INFO")
Definition at line 535 of file custom_logger.py.
WARN_ID
int src.utils.backup.custom_logger.WARN_ID = 36
Definition at line 124 of file custom_logger.py.