name: email_classifier
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - numpy
  - numba
  - doit
  - beautifulsoup4
  - scikit-learn
  - pandas
  - dash
  - dash-bootstrap-components
  - pip:
    - nltk
    - google-api-python-client
    - google-auth-httplib2
    - google-auth-oauthlib