name: email_classifier
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - numpy
  - numba
  - doit
  - beautifulsoup4
  - scikit-learn
  - pandas
  - plotly
  - pip:
    - nltk