name: acme_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - nltk
  - jsonpickle
  - doit
  - numpy
  - numba
  - pandas
  - plotly
  - sqlalchemy
  - beautifulsoup4
  - scikit-learn
  - pygraphviz
#  - pytest
#  - psycopg2
#  - python-graphviz
#  - google-auth-oauthlib
#  - google-api-python-client
#  - google-auth-httplib2
