ACME: src.email_caching.cache_class_defs.EmailDB Class Reference
src.email_caching.cache_class_defs.EmailDB Class Reference
Public Member Functions
None __init__ (self, Optional[Union[bytes, str, Path]] db_path=None, Optional[Union[List[str], str]] table_names=None, Optional[Union[List[str], str]] column_names=None, Dict[str, Any] dtype_mapping=None)
def add_row (self, str table_name, Optional[str] db_label=None, Optional[Tuple[int]] curs_idx=None, **Dict[str, Any] column_datas)
None consolidate_mem_to_disk (self, Optional[Union[str, Union[List[str], Tuple[str]]]] table_names=None)
This function allows for multiple nested context blocks that can inspect existing contents of primary DB but then perform updates and changes to data on an in-memory copy for performance purposes.
Tuple[str, Any] select (self, Optional[Union[str, List[str]]] table_names=None, Optional[Union[str, List[str]]] column_names=None, Optional[Union[List[str], str]] filters=None)
Path database (self)
Returns a pathlib.Path object pointing to our primary db connection for this instance.
None database (self, Union[str, bytes, Path] database)
Dict[str, List[str]] column_names (self)
A mapping of the column names that can be found in a given table.
List[str] table_names (self)
A list of strings, where each element in the list is the name of a table in the main DB.
sqlt3.Connection connection (self)
Calling this property requires that we have made a previous call to self.__call__() in order to properly initialize our active base sqlite3.Connection.
Tuple[sqlt3.Cursor, Tuple[int]] cursor (self)
None commit (self)
def __call__ (self, Optional[str] db_label=None, Optional[Union[bytes, str, Path]] database=None, Optional[float] timeout=None, Optional[int] detect_types=None, Optional[str] isolation_level=None, bool check_same_thread=None, Optional[Type[sqlt3.Connection]] factory=None, Optional[int] cached_statements=None)
def __enter__ (self)
def __exit__ (self, exc_type, exc_val, exc_tb)
def add_row (self, str table_name, str db_label, tuple curs_idx=None, **dict row_obj)
Public Attributes
attached_dbs
database
Static Public Attributes
int
float
bool
Private Member Functions
def _sanitize_column_names_list (self, column_names)
bool _add_to_keys (self, Union[str, Path] db_name, str db_label=None)
def _establish_new_connection (self, Optional[Union[str, Path]] database=None, Optional[float] timeout=None, Optional[int] detect_types=None, Optional[int] isolation_level=None, Optional[bool] check_same_thread=None, Optional[FunctionType] factory=None, Optional[int] cached_statements=None, Optional[bool] do_register_tables=True)
def _register_table (self, dict attrs_dict, Optional[sqlt3.Connection] con=None, Optional[sqlt3.Cursor] curs=None)
def _register_index (self)
Private Attributes
_translation
_table_registry_sql_attrs
_table_mapped_column_names
_table_names
_column_names
_con
_curs
_entry_ordinals
_uncommitted
_database
Static Private Attributes
dictionary __table_attr_template__
A list of DB connections, this list should only grow when creating a new context, and should only grow to contain more than 1 connection when the caller creates nested contexts.
string _table_registry_sql
Detailed Description
Definition at line 48 of file cache_class_defs.py.
Constructor & Destructor Documentation
__init__()
None src.email_caching.cache_class_defs.EmailDB.__init__ (self, Optional[Union[bytes,str,Path]] db_path = None, Optional[Union[List[str], str]] table_names = None, Optional[Union[List[str], str]] column_names = None, Dict[str,Any] dtype_mapping = None)
Reimplemented from src.db_tools.db_class_defs.DBBase.
Definition at line 50 of file cache_class_defs.py.
Member Function Documentation
__call__()
def src.db_tools.db_class_defs.DBBase.__call__ (self, Optional[str] db_label = None, Optional[Union[bytes, str, Path]] database = None, Optional[float] timeout = None, Optional[int] detect_types = None, Optional[str] isolation_level = None, bool check_same_thread = None, Optional[Type[sqlt3.Connection]] factory = None, Optional[int] cached_statements = None) inherited
Allows us to specific instantiation arguments for each new connection we create when the caller uses
with-blocks.
This allows the user to create only a single instance of this database manager object and then create multiple
nested contexts that can each add another database reference for us to connect to.
:param db_label: A string representing the shorthand name to the database we will be connecting to
:type db_label:
:param database: OPTIONAL;
:type database:
:param timeout: OPTIONAL;
:type timeout:
:param detect_types: OPTIONAL;
:type detect_types:
:param isolation_level: OPTIONAL;
:type isolation_level:
:param check_same_thread: OPTIONAL;
:type check_same_thread:
:param factory: OPTIONAL;
:type factory:
:param cached_statements:
:type cached_statements:
:return:
:rtype:
Definition at line 446 of file db_class_defs.py.
References src.db_tools.db_class_defs.DBBase._add_to_keys(), src.db_tools.db_class_defs.DBBase._con, src.db_tools.db_class_defs.DBBase._database, src.db_tools.db_class_defs.DBBase._entry_ordinals, src.db_tools.db_class_defs.DBBase._establish_new_connection(), src.db_tools.db_class_defs.DBBase._table_names, src.db_tools.db_class_defs.DBBase._table_registry_sql_attrs, src.db_tools.db_class_defs.DBBase.attached_dbs, src.db_tools.db_class_defs.DBBase.commit(), src.db_tools.db_class_defs.DBBase.connection(), src.db_tools.db_class_defs.DBBase.cursor(), and src.db_tools.db_class_defs.DBBase.database.
__enter__()
def src.db_tools.db_class_defs.DBBase.__enter__ (self) inherited
Called when creating a new context block, E.G.:
::
    with DBBase(*args) as db:
        # do stuff with db knowing you have a proper connection
        # and any used resources will be safely released when this context exits.
Note: It is acceptable and often encouraged to nest context blocks to create limiting scopes for short lived
      resource usage.
:return:
:rtype:
Definition at line 516 of file db_class_defs.py.
__exit__()
def src.db_tools.db_class_defs.DBBase.__exit__ (self, exc_type, exc_val, exc_tb) inherited
 Exit a context and release any resources created under the scope of that context.
:param exc_type:
:type exc_type:
:param exc_val:
:type exc_val:
:param exc_tb:
:type exc_tb:
:return:
:rtype:
Reimplemented in src.db_tools.db_class_defs.ThreadedDBBase.
Definition at line 532 of file db_class_defs.py.
References src.db_tools.db_class_defs.DBBase._con, src.db_tools.db_class_defs.DBBase._curs, src.db_tools.db_class_defs.DBBase._entry_ordinals, src.db_tools.db_class_defs.DBBase._table_names, src.db_tools.db_class_defs.DBBase._table_registry_sql_attrs, and src.db_tools.db_class_defs.DBBase._uncommitted.
_add_to_keys()
bool src.db_tools.db_class_defs.DBBase._add_to_keys (self, Union[str, Path] db_name, str db_label = None) private inherited
Definition at line 268 of file db_class_defs.py.
References src.db_tools.db_class_defs.DBBase.attached_dbs.
Referenced by src.db_tools.db_class_defs.DBBase.__call__().
_establish_new_connection()
def src.db_tools.db_class_defs.DBBase._establish_new_connection (self, Optional[Union[str,Path]] database = None, Optional[float] timeout = None, Optional[int] detect_types = None, Optional[int] isolation_level = None, Optional[bool] check_same_thread = None, Optional[FunctionType] factory = None, Optional[int] cached_statements = None, Optional[bool] do_register_tables = True) private inherited
A private class function that properly creates a new connection and sets up the required mapping references
to handle that connection in and out of context blocks.
For greater detail on this function's parameters, see sqlite3.connect(...) documentation.
:param database: OPTIONAL; Defaults to self._database;
                The absolute or relative path to the database we should connect to. This an also be "memory"
:type database: Optional[Union[str,Path]]
:param timeout: OPTIONAL; Defaults to self._timeout;
                Specifies how long attempted transactions should wait to timeout.
:type timeout: Optional[float]
:param detect_types: OPTIONAL; Defaults to self._detect_types;
                    detect_types defaults to 0 (i. e. off, no type detection), you can set it to any combination
                    of PARSE_DECLTYPES and PARSE_COLNAMES to turn type detection on. Due to SQLite behaviour,
                    types can’t be detected for generated fields (for example max(data)), even when detect_types
                    parameter is set. In such case, the returned type is str.
:type detect_types: Optional[int]
:param isolation_level: OPTIONAL; Defaults to self._isolation_level;
                        Get or set the current default isolation level.
                         None for autocommit mode or one of
                            “DEFERRED”,
                            “IMMEDIATE”
                            “EXCLUSIVE”.
                        See section Controlling Transactions for a more detailed explanation.
                        (https://docs.python.org/3/library/sqlite3.html#sqlite3-controlling-transactions)
:type isolation_level: Optional[int]
:param check_same_thread: OPTIONAL; Defaults to self._check_same_thread;
                          By default, check_same_thread is True and only the creating thread may use the
                          connection. If set False, the returned connection may be shared across multiple threads.
                          When using multiple threads with the same connection writing operations should be
                          serialized by the user to avoid data corruption.
:type check_same_thread: Optional[bool]
:param factory: OPTIONAL; Defaults to self._factory;
                By default, the sqlite3 module uses its Connection class for the connect call.
                You can, however, subclass the Connection class and make connect() use your class instead by
                providing your class for the factory parameter.
:type factory: Optional[FunctionType]
:param cached_statements: OPTIONAL; Defaults to self._cached_statements;
                          The sqlite3 module internally uses a statement cache to avoid SQL parsing overhead.
                          If you want to explicitly set the number of statements that are cached for the connection,
                          you can set the cached_statements parameter. The currently implemented default is to
                          cache 100 statements.
:type cached_statements: Optional[int]
:param do_register_tables: OPTIONAL; Defaults to self._do_register_tables;
                           A bool value indicating if the new connection must have the same table schema as our
                           primary connection.
                           This is implicitly mandatory when setting up the primary connection itself.
:type do_register_tables: Optional[bool]
:return: No return value
:rtype: None
Definition at line 361 of file db_class_defs.py.
References src.db_tools.db_class_defs.DBBase._con, src.db_tools.db_class_defs.DBBase._curs, src.db_tools.db_class_defs.DBBase._database, src.db_tools.db_class_defs.DBBase._register_table(), src.db_tools.db_class_defs.DBBase._table_registry_sql_attrs, and src.db_tools.db_class_defs.DBBase.table_names().
Referenced by src.db_tools.db_class_defs.DBBase.__call__().
_register_index()
def src.db_tools.db_class_defs.DBBase._register_index (self) private inherited
Definition at line 633 of file db_class_defs.py.
_register_table()
def src.db_tools.db_class_defs.DBBase._register_table (self, dict attrs_dict, Optional[sqlt3.Connection] con = None, Optional[sqlt3.Cursor] curs = None) private inherited
Definition at line 611 of file db_class_defs.py.
References src.db_tools.db_class_defs.DBBase._table_registry_sql, src.db_tools.db_class_defs.DBBase._uncommitted, and src.db_tools.db_class_defs.DBBase.connection().
Referenced by src.db_tools.db_class_defs.DBBase._establish_new_connection().
_sanitize_column_names_list()
def src.db_tools.db_class_defs.DBBase._sanitize_column_names_list (self, column_names) private inherited
Definition at line 193 of file db_class_defs.py.
References src.db_tools.db_class_defs.DBBase._table_names.
add_row() [1/2]
def src.email_caching.cache_class_defs.EmailDB.add_row (self, str table_name, Optional[str] db_label = None, Optional[Tuple[int]] curs_idx = None, **Dict[str, Any] column_datas)
Definition at line 62 of file cache_class_defs.py.
References src.email_caching.cache_class_defs.EmailDB._translation.
Referenced by src.db_tools.db_class_defs.ThreadedDBBase.enqueue_add_row().
add_row() [2/2]
def src.db_tools.db_class_defs.DBBase.add_row (self, str table_name, str db_label, tuple curs_idx = None, **dict row_obj) inherited
Definition at line 747 of file db_class_defs.py.
References src.db_tools.db_class_defs.DBBase._con, src.db_tools.db_class_defs.DBBase._curs, src.db_tools.db_class_defs.DBBase._uncommitted, src.db_tools.db_class_defs.DBBase.connection(), and src.db_tools.db_class_defs.DBBase.cursor().
Referenced by src.db_tools.db_class_defs.ThreadedDBBase.enqueue_add_row().
column_names()
Dict[str,List[str]] src.db_tools.db_class_defs.DBBase.column_names (self) inherited
A mapping of the column names that can be found in a given table.
The elements of _table_names can be used as keys to map a table's name to the associated list of column names.
A mapping of the column names that can be found in a given table. The elements of _table_names can be used as
keys to map a table's name to the associated list of column names.
Definition at line 216 of file db_class_defs.py.
References src.db_tools.db_class_defs.DBBase._column_names.
commit()
None src.db_tools.db_class_defs.DBBase.commit (self) inherited
Call con.commit() for all active connections that has yet uncommitted changes.
:return: None
:rtype: None
Definition at line 308 of file db_class_defs.py.
References src.db_tools.db_class_defs.DBBase._uncommitted.
Referenced by src.db_tools.db_class_defs.DBBase.__call__(), and src.db_tools.db_class_defs.DBBase.consolidate_mem_to_disk().
connection()
sqlt3.Connection src.db_tools.db_class_defs.DBBase.connection (self) inherited
Calling this property requires that we have made a previous call to self.__call__() in order to properly initialize our active base sqlite3.Connection.
:return: A reference to our most recently created sqlite3.Connection object. :rtype: sqlite3.Connection
Definition at line 257 of file db_class_defs.py.
References src.db_tools.db_class_defs.DBBase._con.
Referenced by src.db_tools.db_class_defs.DBBase.__call__(), src.db_tools.db_class_defs.DBBase._register_table(), src.db_tools.db_class_defs.DBBase.add_row(), and src.db_tools.db_class_defs.DBBase.cursor().
consolidate_mem_to_disk()
None src.email_caching.cache_class_defs.EmailDB.consolidate_mem_to_disk (self, Optional[Union[str,Union[List[str],Tuple[str]]]] table_names = None)
This function allows for multiple nested context blocks that can inspect existing contents of primary DB but then perform updates and changes to data on an in-memory copy for performance purposes.
Then when the context closes, we call consolidate_mem_to_disk and update the primary DB according to the state of the in-memory image.
:param table_names: OPTIONAL; Defaults to None; Allows either a string or a iterable collection of strings that specifies which tables from the in-memory image should be applied as updates to the primary database connection. :type table_names: Optional[Union[str, Union[List[str], Tuple[str]]]]
:return: No return value :rtype: None
Reimplemented from src.db_tools.db_class_defs.DBBase.
Definition at line 75 of file cache_class_defs.py.
References src.db_tools.db_class_defs.DBBase._con.
cursor()
Tuple[sqlt3.Cursor, Tuple[int]] src.db_tools.db_class_defs.DBBase.cursor (self) inherited
Definition at line 264 of file db_class_defs.py.
References src.db_tools.db_class_defs.DBBase._curs, and src.db_tools.db_class_defs.DBBase.connection().
Referenced by src.db_tools.db_class_defs.DBBase.__call__(), and src.db_tools.db_class_defs.DBBase.add_row().
database() [1/2]
Path src.db_tools.db_class_defs.DBBase.database (self) inherited
Returns a pathlib.Path object pointing to our primary db connection for this instance.
Returns a pathlib.Path object pointing to our primary db connection for this instance.
Definition at line 231 of file db_class_defs.py.
References src.db_tools.db_class_defs.DBBase._database, and src.db_tools.db_class_defs.DBBase.database.
Referenced by src.db_tools.db_class_defs.DBBase.__call__(), and src.db_tools.db_class_defs.DBBase.__del__().
database() [2/2]
None src.db_tools.db_class_defs.DBBase.database (self, Union[str, bytes, Path] database) inherited
Definition at line 236 of file db_class_defs.py.
References src.db_tools.db_class_defs.DBBase.attached_dbs, and src.db_tools.db_class_defs.DBBase.database.
Referenced by src.db_tools.db_class_defs.DBBase.__call__(), and src.db_tools.db_class_defs.DBBase.__del__().
select()
Tuple[str, Any] src.email_caching.cache_class_defs.EmailDB.select (self, Optional[Union[str, List[str]]] table_names = None, Optional[Union[str,List[str]]] column_names = None, Optional[Union[List[str], str]] filters = None)
This is a generator function that will extract all rows in the requested table(s), and expose the data in
the optionally defined columns, using the optionally defined filters.
The resulting SQLite statement will look something like this:
::
    SELECT
        column_list
    FROM
        table
    WHERE
        search_condition;
Note:
    1)
        The table_names argument will be filtered against the table names actually present in the main database.
        If a table name found in table_names does not exist in the main database for this DBBase object, then it
        will be ignored and any filters associated with that table name will also be ignored.
    2)
        The filters argument must be submitted as a valid sql WHERE statement.
        Consider the following separate examples; the names used, `column_x`, are contrived examples.
        Your string must use your table's valid column names.
        If you provide a list of strings, we assume that each string in filters that starts with `WHERE` is an
        independent and should be paired with the table name of the same list position in the table_names. All
        strings in the filters list that do not start with `WHERE` are assumed to be part of the first previous
        list element that started with `WHERE`. We assume the first element of the filters list must start with
        `WHERE` and will prepend to that string otherwise.
        if table_names is given as a single string, then we will only use the first where statement from
        the given list of filters.
    ::
        - WHERE column_1 = 100;
        - WHERE column_2 IN (1,2,3);
        - WHERE column_3 LIKE 'An%';
        - WHERE column_4 BETWEEN 10 AND 20;
        - WHERE column_1 = 100 OR column_2 IN (1,2,3);
        - WHERE column_3 LIKE 'An%' AND column_4 BETWEEN 10 AND 20;
:param table_names: A string, or a list of strings, giving the table names we should query in this select.
:type table_names: Union[str, List[str]]
:param column_names: An optional string, or list of strings, that give the names of the columns we should
                     retrieve from the table(s) given in table_names.
:type column_names: Union[str, List[str]]
:param filters: An optional string, or list of strings, that specify the filtering conditions we should employ
                to restrict what data is returned.
:type filters: Union[str, List[str]]
:return: A 2-Tuple, where the first element is the name of the source table, and the second is the row contents
:rtype:
Reimplemented from src.db_tools.db_class_defs.DBBase.
Definition at line 86 of file cache_class_defs.py.
References src.db_tools.db_class_defs.DBBase._column_names, and src.db_tools.db_class_defs.DBBase.table_names().
table_names()
List[str] src.db_tools.db_class_defs.DBBase.table_names (self) inherited
A list of strings, where each element in the list is the name of a table in the main DB.
A list of strings, where each element in the list is the name of a table in the main DB
Definition at line 224 of file db_class_defs.py.
References src.db_tools.db_class_defs.DBBase._table_names.
Referenced by src.db_tools.db_class_defs.DBBase._establish_new_connection(), src.body_extraction.cache_class_defs.MessageBodyDB.select(), src.email_caching.cache_class_defs.EmailDB.select(), and src.lemma_extraction.cache_class_defs.LemmaDB.select().
Member Data Documentation
__table_attr_template__
dictionary src.db_tools.db_class_defs.DBBase.__table_attr_template__ static private inherited
Initial value:
=  {
        "db_label": "main.",
        "pkey_name": "id",
        "pkey_type": DB_SUPPORTED_TYPES[int],
        "data_points": "",
    }
A list of DB connections, this list should only grow when creating a new context, and should only grow to contain more than 1 connection when the caller creates nested contexts.
A nested list of temporary database connections. This allows the caller to create cursors that persist through the lifespan of a given context and be assured those cursors will be properly released when the context closes.
Definition at line 132 of file db_class_defs.py.
_column_names
src.db_tools.db_class_defs.DBBase._column_names private inherited
Definition at line 168 of file db_class_defs.py.
Referenced by src.db_tools.db_class_defs.DBBase.column_names(), src.body_extraction.cache_class_defs.MessageBodyDB.select(), src.email_caching.cache_class_defs.EmailDB.select(), and src.lemma_extraction.cache_class_defs.LemmaDB.select().
_con
src.db_tools.db_class_defs.DBBase._con private inherited
Definition at line 169 of file db_class_defs.py.
Referenced by src.db_tools.db_class_defs.DBBase.__call__(), src.db_tools.db_class_defs.DBBase.__del__(), src.db_tools.db_class_defs.DBBase.__exit__(), src.db_tools.db_class_defs.ThreadedDBBase.__exit__(), src.db_tools.db_class_defs.DBBase._establish_new_connection(), src.db_tools.db_class_defs.DBBase.add_row(), src.db_tools.db_class_defs.DBBase.connection(), src.db_tools.db_class_defs.DBBase.consolidate_mem_to_disk(), and src.email_caching.cache_class_defs.EmailDB.consolidate_mem_to_disk().
_curs
src.db_tools.db_class_defs.DBBase._curs private inherited
Definition at line 170 of file db_class_defs.py.
Referenced by src.db_tools.db_class_defs.DBBase.__del__(), src.db_tools.db_class_defs.DBBase.__exit__(), src.db_tools.db_class_defs.DBBase._establish_new_connection(), src.db_tools.db_class_defs.DBBase.add_row(), and src.db_tools.db_class_defs.DBBase.cursor().
_database
src.db_tools.db_class_defs.DBBase._database private inherited
Definition at line 248 of file db_class_defs.py.
Referenced by src.db_tools.db_class_defs.DBBase.__call__(), src.db_tools.db_class_defs.DBBase._establish_new_connection(), and src.db_tools.db_class_defs.DBBase.database().
_entry_ordinals
src.db_tools.db_class_defs.DBBase._entry_ordinals private inherited
Definition at line 171 of file db_class_defs.py.
Referenced by src.db_tools.db_class_defs.DBBase.__call__(), and src.db_tools.db_class_defs.DBBase.__exit__().
_table_mapped_column_names
src.db_tools.db_class_defs.DBBase._table_mapped_column_names private inherited
Definition at line 166 of file db_class_defs.py.
_table_names
src.db_tools.db_class_defs.DBBase._table_names private inherited
Definition at line 167 of file db_class_defs.py.
Referenced by src.db_tools.db_class_defs.DBBase.__call__(), src.db_tools.db_class_defs.DBBase.__exit__(), src.db_tools.db_class_defs.DBBase._sanitize_column_names_list(), and src.db_tools.db_class_defs.DBBase.table_names().
_table_registry_sql
string src.db_tools.db_class_defs.DBBase._table_registry_sql static private inherited
Initial value:
=  """
    CREATE TABLE IF NOT EXISTS {db_label}{table_name} (
        {pkey_name} {pkey_type} PRIMARY KEY NOT NULL,{data_points}
    );
    """
Definition at line 145 of file db_class_defs.py.
Referenced by src.db_tools.db_class_defs.DBBase._register_table().
_table_registry_sql_attrs
src.db_tools.db_class_defs.DBBase._table_registry_sql_attrs private inherited
Definition at line 165 of file db_class_defs.py.
Referenced by src.db_tools.db_class_defs.DBBase.__call__(), src.db_tools.db_class_defs.DBBase.__exit__(), and src.db_tools.db_class_defs.DBBase._establish_new_connection().
_translation
src.email_caching.cache_class_defs.EmailDB._translation private
Definition at line 59 of file cache_class_defs.py.
Referenced by src.email_caching.cache_class_defs.EmailDB.add_row().
_uncommitted
src.db_tools.db_class_defs.DBBase._uncommitted private inherited
Definition at line 172 of file db_class_defs.py.
Referenced by src.db_tools.db_class_defs.DBBase.__exit__(), src.db_tools.db_class_defs.DBBase._register_table(), src.db_tools.db_class_defs.DBBase.add_row(), and src.db_tools.db_class_defs.DBBase.commit().
attached_dbs
src.db_tools.db_class_defs.DBBase.attached_dbs inherited
Definition at line 173 of file db_class_defs.py.
Referenced by src.db_tools.db_class_defs.DBBase.__call__(), src.db_tools.db_class_defs.DBBase.__del__(), src.db_tools.db_class_defs.DBBase._add_to_keys(), and src.db_tools.db_class_defs.DBBase.database().
bool
src.db_tools.db_class_defs.DBBase.bool static inherited
Definition at line 156 of file db_class_defs.py.
database
src.db_tools.db_class_defs.DBBase.database inherited
Definition at line 176 of file db_class_defs.py.
Referenced by src.db_tools.db_class_defs.DBBase.__call__(), src.db_tools.db_class_defs.DBBase.__del__(), and src.db_tools.db_class_defs.DBBase.database().
float
src.db_tools.db_class_defs.DBBase.float static inherited
Definition at line 153 of file db_class_defs.py.
int
src.db_tools.db_class_defs.DBBase.int static inherited
Definition at line 142 of file db_class_defs.py.
The documentation for this class was generated from the following file:
src/email_caching/cache_class_defs.py