ACME: src.utils Namespace Reference
src.utils Namespace Reference
::main
Namespaces
__main__
backup
constant_globals
custom_logger
pathing_defs
Classes
class PoliteDownloader
Subclassed the Downloader provided by nltk to give better control over the garbage console output the default implementation forced on us.
class JPickleSerializable
An abstract base class that represents a generic interface for custom class objects that will end up being cached as byte strings in a database.
class TaggerBase
An extension of the JPickleSerializable interface that ensures our custom classes can properly handle our custom character substitutions after being serialized/deserialized via the JPickleSerializable interface.
Functions
def alias_keys (dict d)
A helper function for converting semantically meaningful, and detailed attribute keys into conveniently short alias keys.
def handle_warning_about_unexpected_exceptions (BaseException be, *Iterable details)
def undo_pickle (fd_or_data, bool is_file=True)
def do_pickle (obj, fd=None, protocol=-1)
A convenience function for quickly creating python pickle objects that temporarily disables garbage collection during the serialization process.
List[str] to_list (obj)
A convenience function for ensuring an object is a list of strings.
Variables
nltk_packages = Path(cache_folder.root).resolve().absolute().joinpath("nltk_packages")
nltk_path_str = str(nltk_packages)
parents
True
exist_ok
download_dir
nltk = None
nltk_loader = None
exc_info
txt = PoliteDownloader().list(nltk_path_str, color_coded=True, skip_not_installed=True)
plain_info_logger = get_logger("EmailClassifier",__name__+": plain logger",level="INFO")
src_warning_logger = get_logger("EmailClassifier",__name__+": warning",level="WARNING")
proj_base_info_logger = get_logger("EmailClassifier",__name__+": root logger",level="INFO")
The root logger object for the project.
cridentials_path = project_root_folder.joinpath("src/environ_vars.json")
check and optionally set environment variables for imap server login
cridentials = json.loads(cridentials_path.read_text("utf-8"))
string confirmation = ""
GLOBAL_IMAP_EMAIL_ACCOUNT = cridentials["EMAIL_ACCOUNT"]
GLOBAL_IMAP_PASSWORD = cridentials["PASSWORD"]
GLOBAL_IMAP_HOST = cridentials["EMAIL_SERVER_HOST"]
string DB_INTEGER = "INTEGER"
defining global references to the data types our database objects can support.
string DB_NULL = "NULL"
string DB_REAL = "REAL"
string DB_TEXT = "TEXT"
string DB_BLOB = "BLOB"
string PROJ_CUSTOM_CLASSES = "COMPLEX_JSON"
string PROJ_SIMPLE_JSON = "SIMPLE_JSON"
dictionary DB_SUPPORTED_TYPES
project scoped dictionaries
dictionary DB_PATH_DICT
A mapping of our projects specific database paths.
dictionary TABLE_NAMES
A mapping of table names where each key corresponds to a key from DB_PATH_DICT above, and the values are lists of strings defining the names of the tables that database should have.
Detailed Description
::main
@src.utils.__init__.py
The project's actual __init__.py file, this is where we initialize all of the shared dependencies for the despirit
submodules of the project.
Should a user wish to extract specific components from this project, they should also always take the src/utils folder
along with their chosen submodule.
@src.utils.__main__.py
This is where we handle registering our custom converters and adapters that tells the sqlite3 package how to handle our
custom data structures.
Function Documentation
alias_keys()
def src.utils.alias_keys (dict d)
A helper function for converting semantically meaningful, and detailed attribute keys into conveniently short alias keys.
Definition at line 172 of file __init__.py.
do_pickle()
def src.utils.do_pickle (obj, fd = None, protocol = -1)
A convenience function for quickly creating python pickle objects that temporarily disables garbage collection during the serialization process.
In some cases, turning garbage collection off can represent a 20x speedup in the time it takes to pickle an object.
Definition at line 264 of file __init__.py.
References src.utils.handle_warning_about_unexpected_exceptions().
Referenced by src.email_caching.downloader.pickle_dump().
handle_warning_about_unexpected_exceptions()
def src.utils.handle_warning_about_unexpected_exceptions (BaseException be, *Iterable details)
Definition at line 241 of file __init__.py.
Referenced by src.utils.do_pickle(), and src.utils.undo_pickle().
to_list()
List[str] src.utils.to_list (obj)
A convenience function for ensuring an object is a list of strings.
This function is called in several places. It ensures that function arguments of type Union[Path,AnyStr,List[Union[Path,AnyStr]]] will be resolved to a list of strings.
Definition at line 317 of file __init__.py.
undo_pickle()
def src.utils.undo_pickle (fd_or_data, bool is_file = True)
Definition at line 247 of file __init__.py.
References src.utils.handle_warning_about_unexpected_exceptions().
Referenced by src.email_caching.downloader.pickle_load().
Variable Documentation
confirmation
string src.utils.confirmation = ""
Definition at line 147 of file __init__.py.
cridentials
src.utils.cridentials = json.loads(cridentials_path.read_text("utf-8"))
Definition at line 143 of file __init__.py.
cridentials_path
src.utils.cridentials_path = project_root_folder.joinpath("src/environ_vars.json")
check and optionally set environment variables for imap server login
Definition at line 141 of file __init__.py.
DB_BLOB
string src.utils.DB_BLOB = "BLOB"
Definition at line 187 of file __init__.py.
DB_INTEGER
string src.utils.DB_INTEGER = "INTEGER"
defining global references to the data types our database objects can support.
Definition at line 183 of file __init__.py.
DB_NULL
string src.utils.DB_NULL = "NULL"
Definition at line 184 of file __init__.py.
DB_PATH_DICT
dictionary src.utils.DB_PATH_DICT
Initial value:
 =  {
     "email_cache":cache_folder.joinpath("sql3_email.db"),
     "body_cache":cache_folder.joinpath("sql3_message_body.db"),
     "lemma_cache":cache_folder.joinpath("sql3_extracted_lemma.db"),
     "consolidated_cache":cache_folder.joinpath("sql3_consolidated.db")
 }
A mapping of our projects specific database paths.
If a user wishes to customize database naming, this is where they should make those changes.
Definition at line 220 of file __init__.py.
DB_REAL
string src.utils.DB_REAL = "REAL"
Definition at line 185 of file __init__.py.
DB_SUPPORTED_TYPES
dictionary src.utils.DB_SUPPORTED_TYPES
Initial value:
 =  {
     "int":DB_INTEGER,
     "integer":DB_INTEGER,
     int:DB_INTEGER,
     "None":DB_NULL,
     "NULL":DB_NULL,
     None:DB_NULL,
     "float":DB_REAL,
     "REAL":DB_REAL,
     float:DB_REAL,
     "str":DB_TEXT,
     "TEXT":DB_TEXT,
     str:DB_TEXT,
     "bytes":DB_BLOB,
     "BLOB":DB_BLOB,
     bytes:DB_BLOB,
     "custom_cls":PROJ_CUSTOM_CLASSES,
     PROJ_CUSTOM_CLASSES:PROJ_CUSTOM_CLASSES,
     PROJ_CUSTOM_CLASSES.lower():PROJ_CUSTOM_CLASSES,
     PROJ_SIMPLE_JSON:PROJ_SIMPLE_JSON,
     PROJ_SIMPLE_JSON.lower():PROJ_SIMPLE_JSON,
 }
project scoped dictionaries
Definition at line 193 of file __init__.py.
DB_TEXT
string src.utils.DB_TEXT = "TEXT"
Definition at line 186 of file __init__.py.
download_dir
src.utils.download_dir
Definition at line 39 of file __init__.py.
exc_info
src.utils.exc_info
Definition at line 49 of file __init__.py.
exist_ok
src.utils.exist_ok
Definition at line 37 of file __init__.py.
GLOBAL_IMAP_EMAIL_ACCOUNT
src.utils.GLOBAL_IMAP_EMAIL_ACCOUNT = cridentials["EMAIL_ACCOUNT"]
Definition at line 165 of file __init__.py.
GLOBAL_IMAP_HOST
src.utils.GLOBAL_IMAP_HOST = cridentials["EMAIL_SERVER_HOST"]
Definition at line 167 of file __init__.py.
GLOBAL_IMAP_PASSWORD
src.utils.GLOBAL_IMAP_PASSWORD = cridentials["PASSWORD"]
Definition at line 166 of file __init__.py.
nltk
src.utils.nltk = None
Definition at line 47 of file __init__.py.
nltk_loader
src.utils.nltk_loader = None
Definition at line 48 of file __init__.py.
nltk_packages
src.utils.nltk_packages = Path(cache_folder.root).resolve().absolute().joinpath("nltk_packages")
Definition at line 31 of file __init__.py.
nltk_path_str
src.utils.nltk_path_str = str(nltk_packages)
Definition at line 32 of file __init__.py.
parents
src.utils.parents
Definition at line 37 of file __init__.py.
plain_info_logger
src.utils.plain_info_logger = get_logger("EmailClassifier",__name__+": plain logger",level="INFO")
Definition at line 130 of file __init__.py.
proj_base_info_logger
src.utils.proj_base_info_logger = get_logger("EmailClassifier",__name__+": root logger",level="INFO")
The root logger object for the project.
Definition at line 136 of file __init__.py.
PROJ_CUSTOM_CLASSES
string src.utils.PROJ_CUSTOM_CLASSES = "COMPLEX_JSON"
Definition at line 188 of file __init__.py.
PROJ_SIMPLE_JSON
string src.utils.PROJ_SIMPLE_JSON = "SIMPLE_JSON"
Definition at line 189 of file __init__.py.
src_warning_logger
src.utils.src_warning_logger = get_logger("EmailClassifier",__name__+": warning",level="WARNING")
Definition at line 131 of file __init__.py.
TABLE_NAMES
dictionary src.utils.TABLE_NAMES
Initial value:
 =  {
     "email_cache":["emails"],
     "body_cache":["message_body"],
     "lemma_cache":["all_lemma", "no_stopwords_lemma"],
 }
A mapping of table names where each key corresponds to a key from DB_PATH_DICT above, and the values are lists of strings defining the names of the tables that database should have.
Definition at line 231 of file __init__.py.
True
src.utils.True
Definition at line 37 of file __init__.py.
txt
src.utils.txt = PoliteDownloader().list(nltk_path_str, color_coded=True, skip_not_installed=True)
Definition at line 128 of file __init__.py.