ACME: src.eralchemy.helpers Namespace Reference
src.eralchemy.helpers Namespace Reference
Functions
def fail (message, *args)
def check_args (args)
def check_args_has_attributes (args)
def check_args_has_attribute (args, name)
Function Documentation
check_args()
def src.eralchemy.helpers.check_args (args)
Checks that the args are coherent.
Definition at line 11 of file helpers.py.
References src.eralchemy.helpers.check_args_has_attributes(), and src.eralchemy.helpers.fail().
check_args_has_attribute()
def src.eralchemy.helpers.check_args_has_attribute (args, name)
Definition at line 36 of file helpers.py.
Referenced by src.eralchemy.helpers.check_args_has_attributes().
check_args_has_attributes()
def src.eralchemy.helpers.check_args_has_attributes (args)
Definition at line 26 of file helpers.py.
References src.eralchemy.helpers.check_args_has_attribute().
Referenced by src.eralchemy.helpers.check_args().
fail()
def src.eralchemy.helpers.fail (message, * args)
Definition at line 6 of file helpers.py.
Referenced by src.eralchemy.helpers.check_args().