ACME: src.db_tools.database_consolidation Namespace Reference
src.db_tools.database_consolidation Namespace Reference
Functions
def doit_consolidate_databases (List[str] targets, List[str] file_dep)
def consolidate_databases (Path consolidated_db_path, Dict[str, Path] satalite_databases)
None doit_generate_erd (List[str] targets, List[str] file_dep)
Variables
info_logger = get_logger("EmailClassifier",__name__+".consolidation_logger",level="INFO")
_target = Path(__file__).resolve().parent
itr = _target.parts
parents
True
exist_ok
Function Documentation
consolidate_databases()
def src.db_tools.database_consolidation.consolidate_databases (Path consolidated_db_path, Dict[str,Path] satalite_databases)
Definition at line 17 of file database_consolidation.py.
Referenced by src.db_tools.database_consolidation.doit_consolidate_databases().
doit_consolidate_databases()
def src.db_tools.database_consolidation.doit_consolidate_databases (List[str] targets, List[str] file_dep)
Definition at line 13 of file database_consolidation.py.
References src.db_tools.database_consolidation.consolidate_databases().
doit_generate_erd()
None src.db_tools.database_consolidation.doit_generate_erd (List[str] targets, List[str] file_dep)
Definition at line 97 of file database_consolidation.py.
References src.eralchemy.main.render_er().
Variable Documentation
_target
src.db_tools.database_consolidation._target = Path(__file__).resolve().parent private
Definition at line 111 of file database_consolidation.py.
exist_ok
src.db_tools.database_consolidation.exist_ok
Definition at line 116 of file database_consolidation.py.
info_logger
src.db_tools.database_consolidation.info_logger = get_logger("EmailClassifier",__name__+".consolidation_logger",level="INFO")
Definition at line 10 of file database_consolidation.py.
itr
src.db_tools.database_consolidation.itr = _target.parts
Definition at line 112 of file database_consolidation.py.
parents
src.db_tools.database_consolidation.parents
Definition at line 116 of file database_consolidation.py.
True
src.db_tools.database_consolidation.True
Definition at line 116 of file database_consolidation.py.