ACME: src.eralchemy.main Namespace Reference
src.eralchemy.main Namespace Reference
Functions
def cli ()
def get_argparser ()
def intermediary_to_markdown (tables, relationships, output)
def intermediary_to_dot (tables, relationships, output)
def intermediary_to_schema (tables, relationships, output)
def _intermediary_to_markdown (tables, relationships)
def _intermediary_to_dot (tables, relationships)
def all_to_intermediary (filename_or_input, schema=None)
def get_output_mode (output, mode)
def filter_resources (tables, relationships, include_tables=None, include_columns=None, exclude_tables=None, exclude_columns=None)
def render_er (input, output, mode='auto', include_tables=None, include_columns=None, exclude_tables=None, exclude_columns=None, schema=None)
Variables
basestring = str
dictionary switch_input_class_to_method
dictionary switch_output_mode_auto
dictionary switch_output_mode
Function Documentation
_intermediary_to_dot()
def src.eralchemy.main._intermediary_to_dot (tables, relationships) private
 Returns the dot source representing the database in a string.
Definition at line 85 of file main.py.
Referenced by src.eralchemy.main.intermediary_to_dot(), and src.eralchemy.main.intermediary_to_schema().
_intermediary_to_markdown()
def src.eralchemy.main._intermediary_to_markdown (tables, relationships) private
 Returns the er markup source in a string.
Definition at line 78 of file main.py.
Referenced by src.eralchemy.main.intermediary_to_markdown().
all_to_intermediary()
def src.eralchemy.main.all_to_intermediary (filename_or_input, schema = None)
 Dispatch the filename_or_input to the different function to produce the intermediary syntax.
All the supported classes names are in `swich_input_class_to_method`.
The input can also be a list of strings in markdown format or a filename finishing by '.er' containing markdown
format.
Definition at line 123 of file main.py.
References src.eralchemy.sqla.database_to_intermediary(), src.eralchemy.parser.line_iterator_to_intermediary(), and src.eralchemy.parser.markdown_file_to_intermediary().
Referenced by src.eralchemy.main.render_er().
cli()
def src.eralchemy.main.cli ()
Entry point for the application script
Definition at line 22 of file main.py.
References src.body_extraction.cli_entry.check_args(), src.eralchemy.main.get_argparser(), and src.eralchemy.main.render_er().
Referenced by src.eralchemy.main.render_er().
filter_resources()
def src.eralchemy.main.filter_resources (tables, relationships, include_tables = None, include_columns = None, exclude_tables = None, exclude_columns = None)
Include the following:
    1. Tables and relationships with tables present in the include_tables (lst of str, tables names)
    2. Columns (of whichever table) present in the include_columns (lst of str, columns names)
Exclude the following:
    1. Tables and relationships with tables present in the exclude_tables (lst of str, tables names)
    2. Columns (of whichever table) present in the exclude_columns (lst of str, columns names)
Disclosure note:
    All relationships are taken into consideration before ignoring columns.
    In other words, if one excludes primary or foreign keys, it will still keep the relations display amongst tables
Definition at line 177 of file main.py.
Referenced by src.eralchemy.main.render_er().
get_argparser()
def src.eralchemy.main.get_argparser ()
Definition at line 42 of file main.py.
Referenced by src.eralchemy.main.cli().
get_output_mode()
def src.eralchemy.main.get_output_mode (output, mode)
From the output name and the mode returns a the function that will transform the intermediary
representation to the output.
Definition at line 159 of file main.py.
Referenced by src.eralchemy.main.render_er().
intermediary_to_dot()
def src.eralchemy.main.intermediary_to_dot (tables, relationships, output)
 Save the intermediary representation to dot format.
Definition at line 62 of file main.py.
References src.eralchemy.main._intermediary_to_dot().
intermediary_to_markdown()
def src.eralchemy.main.intermediary_to_markdown (tables, relationships, output)
 Saves the intermediary representation to markdown.
Definition at line 55 of file main.py.
References src.eralchemy.main._intermediary_to_markdown().
intermediary_to_schema()
def src.eralchemy.main.intermediary_to_schema (tables, relationships, output)
 Transforms and save the intermediary representation to the file chosen.
Definition at line 69 of file main.py.
References src.eralchemy.main._intermediary_to_dot().
render_er()
def src.eralchemy.main.render_er (input, output, mode = 'auto', include_tables = None, include_columns = None, exclude_tables = None, exclude_columns = None, schema = None)
Transform the metadata into a representation.
:param input: Possible inputs are instances of:
    MetaData: SQLAlchemy Metadata
    DeclarativeMeta: SQLAlchemy declarative Base
:param output: name of the file to output the
:param mode: str in list:
    'er': writes to a file the markup to generate an ER style diagram.
    'graph': writes the image of the ER diagram.
    'dot': write to file the diagram in dot format.
    'auto': choose from the filename:
        '*.er': writes to a file the markup to generate an ER style diagram.
        '.dot': returns the graph in the dot syntax.
        else: return a graph to the format graph
:param include_tables: lst of str, table names to include, None means include all
:param include_columns: lst of str, column names to include, None means include all
:param exclude_tables: lst of str, table names to exclude, None means exclude nothing
:param exclude_columns: lst of str, field names to exclude, None means exclude nothing
:param schema: name of the schema
Definition at line 221 of file main.py.
References src.eralchemy.main.all_to_intermediary(), src.eralchemy.main.cli(), src.eralchemy.main.filter_resources(), and src.eralchemy.main.get_output_mode().
Referenced by src.eralchemy.main.cli(), and src.db_tools.database_consolidation.doit_generate_erd().
Variable Documentation
basestring
src.eralchemy.main.basestring = str
Definition at line 19 of file main.py.
switch_input_class_to_method
dictionary src.eralchemy.main.switch_input_class_to_method
Initial value:
 =  {
     'MetaData': metadata_to_intermediary,
     'DeclarativeMeta': declarative_to_intermediary,
     # For compatibility with Flask-SQLAlchemy
     '_BoundDeclarativeMeta': declarative_to_intermediary,
     # Renamed in Flask-SQLAlchemy 2.3
     'DefaultMeta': declarative_to_intermediary
 }
Definition at line 94 of file main.py.
switch_output_mode
dictionary src.eralchemy.main.switch_output_mode
Initial value:
 =  {
     'er': intermediary_to_markdown,
     'dot': intermediary_to_dot,
 }
Definition at line 117 of file main.py.
switch_output_mode_auto
dictionary src.eralchemy.main.switch_output_mode_auto
Initial value:
 =  {
     'er': intermediary_to_markdown,
     'graph': intermediary_to_schema,
     'dot': intermediary_to_dot
 }
Definition at line 109 of file main.py.