ACME: src.body_extraction.cli_entry Namespace Reference
src.body_extraction.cli_entry Namespace Reference
Functions
def fail (message, *args)
def check_args (args)
def check_args_has_attributes (args)
def check_args_has_attribute (args, name)
def cli ()
def get_argparser ()
Variables
int __version__ = 0,0,1
Detailed Description
The majority of the code for this command line entry point is borrowed from the eralchemy codebase found here:
    https://github.com/Alexis-benoist/eralchemy
Function Documentation
check_args()
def src.body_extraction.cli_entry.check_args (args)
Checks that the args are coherent.
Definition at line 20 of file cli_entry.py.
References src.body_extraction.cli_entry.check_args_has_attributes(), and src.body_extraction.cli_entry.fail().
Referenced by src.body_extraction.cli_entry.cli(), and src.eralchemy.main.cli().
check_args_has_attribute()
def src.body_extraction.cli_entry.check_args_has_attribute (args, name)
Definition at line 45 of file cli_entry.py.
Referenced by src.body_extraction.cli_entry.check_args_has_attributes().
check_args_has_attributes()
def src.body_extraction.cli_entry.check_args_has_attributes (args)
Definition at line 35 of file cli_entry.py.
References src.body_extraction.cli_entry.check_args_has_attribute().
Referenced by src.body_extraction.cli_entry.check_args().
cli()
def src.body_extraction.cli_entry.cli ()
Entry point for the application script
Definition at line 50 of file cli_entry.py.
References src.body_extraction.cli_entry.check_args(), and src.body_extraction.cli_entry.get_argparser().
fail()
def src.body_extraction.cli_entry.fail (message, * args)
Definition at line 15 of file cli_entry.py.
Referenced by src.body_extraction.cli_entry.check_args().
get_argparser()
def src.body_extraction.cli_entry.get_argparser ()
Definition at line 61 of file cli_entry.py.
Referenced by src.body_extraction.cli_entry.cli().
Variable Documentation
__version__
int src.body_extraction.cli_entry.__version__ = 0,0,1 private
Definition at line 12 of file cli_entry.py.