ACME: src.email_caching.downloader Namespace Reference
src.email_caching.downloader Namespace Reference
Functions
def pickle_load (path, mode="rb", default=None)
def pickle_dump (obj, path, mode="wb", protocol=-1)
def _threadable_logic (imap_url, target_email, bad_practice, mail_id, bytes_parser, existing_keys)
None email_downloader (cache_root=None)
def doit_email_downloader (list targets)
Variables
body_structure_splitter = re.compile("\‍)\‍(")
info = get_logger("EmailClassifier",__name__+": downloader status updates",level="INFO")
err_log = get_logger("EmailClassifier",__name__+": downloader error messsage",level="ERROR")
string message_retrieval_code = "(RFC822)"
string header_retrieval_code = "(RFC822.HEADER)"
string structure_retrieval_code = "(BODY)"
string U8 = "UTF-8"
list nums_lst = ["zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine"]
string id_to_str = lambda s:"_".join(nums_lst[i] for i in map(int,s))
here = Path(__file__).resolve().parent
test_cache_target = here.joinpath("test_cache_dir/header_keys.pkl")
parents
True
exist_ok
Function Documentation
_threadable_logic()
def src.email_caching.downloader._threadable_logic (imap_url, target_email, bad_practice, mail_id, bytes_parser, existing_keys) private
Definition at line 61 of file downloader.py.
References src.email_caching.downloader.id_to_str.
doit_email_downloader()
def src.email_caching.downloader.doit_email_downloader (list targets)
Definition at line 152 of file downloader.py.
References src.email_caching.downloader.email_downloader().
email_downloader()
None src.email_caching.downloader.email_downloader (cache_root = None)
Given a path to the root directory for our output data cache, download files from our
email address and cache them as a sqlite3 DB in that location.
:param targets: A list of strings representing directory paths (absolute or relative) for where we should
                cache our downloaded emails.
:return: None
Definition at line 88 of file downloader.py.
Referenced by src.email_caching.downloader.doit_email_downloader().
pickle_dump()
def src.email_caching.downloader.pickle_dump (obj, path, mode = "wb", protocol = -1)
Definition at line 51 of file downloader.py.
References src.utils.do_pickle().
pickle_load()
def src.email_caching.downloader.pickle_load (path, mode = "rb", default = None)
Definition at line 37 of file downloader.py.
References src.utils.undo_pickle().
Variable Documentation
body_structure_splitter
src.email_caching.downloader.body_structure_splitter = re.compile("\‍)\‍(")
Definition at line 22 of file downloader.py.
err_log
src.email_caching.downloader.err_log = get_logger("EmailClassifier",__name__+": downloader error messsage",level="ERROR")
Definition at line 24 of file downloader.py.
exist_ok
src.email_caching.downloader.exist_ok
Definition at line 165 of file downloader.py.
header_retrieval_code
string src.email_caching.downloader.header_retrieval_code = "(RFC822.HEADER)"
Definition at line 30 of file downloader.py.
here
src.email_caching.downloader.here = Path(__file__).resolve().parent
Definition at line 163 of file downloader.py.
id_to_str
string src.email_caching.downloader.id_to_str = lambda s:"_".join(nums_lst[i] for i in map(int,s))
Definition at line 34 of file downloader.py.
Referenced by src.email_caching.downloader._threadable_logic().
info
src.email_caching.downloader.info = get_logger("EmailClassifier",__name__+": downloader status updates",level="INFO")
Definition at line 23 of file downloader.py.
message_retrieval_code
string src.email_caching.downloader.message_retrieval_code = "(RFC822)"
Definition at line 29 of file downloader.py.
nums_lst
list src.email_caching.downloader.nums_lst = ["zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine"]
Definition at line 33 of file downloader.py.
parents
src.email_caching.downloader.parents
Definition at line 165 of file downloader.py.
structure_retrieval_code
string src.email_caching.downloader.structure_retrieval_code = "(BODY)"
Definition at line 31 of file downloader.py.
test_cache_target
src.email_caching.downloader.test_cache_target = here.joinpath("test_cache_dir/header_keys.pkl")
Definition at line 164 of file downloader.py.
True
src.email_caching.downloader.True
Definition at line 165 of file downloader.py.
U8
string src.email_caching.downloader.U8 = "UTF-8"
Definition at line 32 of file downloader.py.