ACME: src.eralchemy.sqla Namespace Reference
src.eralchemy.sqla Namespace Reference
Functions
def relation_to_intermediary (fk)
def format_type (typ)
def format_name (name)
def column_to_intermediary (col, type_formatter=format_type)
def table_to_intermediary (table)
def metadata_to_intermediary (metadata)
def declarative_to_intermediary (base)
def name_for_scalar_relationship (base, local_cls, referred_cls, constraint)
def database_to_intermediary (database_uri, schema=None)
Variables
unicode = str
Function Documentation
column_to_intermediary()
def src.eralchemy.sqla.column_to_intermediary (col, type_formatter = format_type)
Transform an SQLAlchemy Column object to it's intermediary representation.
Definition at line 37 of file sqla.py.
Referenced by src.eralchemy.sqla.table_to_intermediary().
database_to_intermediary()
def src.eralchemy.sqla.database_to_intermediary (database_uri, schema = None)
 Introspect from the database (given the database_uri) to create the intermediary representation.
Definition at line 85 of file sqla.py.
References src.eralchemy.sqla.declarative_to_intermediary().
Referenced by src.eralchemy.main.all_to_intermediary().
declarative_to_intermediary()
def src.eralchemy.sqla.declarative_to_intermediary (base)
 Transform an SQLAlchemy Declarative Base to the intermediary representation.
Definition at line 74 of file sqla.py.
References src.eralchemy.sqla.metadata_to_intermediary().
Referenced by src.eralchemy.sqla.database_to_intermediary().
format_name()
def src.eralchemy.sqla.format_name (name)
 Transforms the name into a nice string representation.
Definition at line 32 of file sqla.py.
References src.eralchemy.sqla.unicode.
Referenced by src.eralchemy.sqla.relation_to_intermediary().
format_type()
def src.eralchemy.sqla.format_type (typ)
 Transforms the type into a nice string representation.
Definition at line 24 of file sqla.py.
References src.eralchemy.sqla.unicode.
metadata_to_intermediary()
def src.eralchemy.sqla.metadata_to_intermediary (metadata)
 Transforms SQLAlchemy metadata to the intermediary representation.
Definition at line 66 of file sqla.py.
References src.eralchemy.sqla.relation_to_intermediary(), and src.eralchemy.sqla.table_to_intermediary().
Referenced by src.eralchemy.sqla.declarative_to_intermediary().
name_for_scalar_relationship()
def src.eralchemy.sqla.name_for_scalar_relationship (base, local_cls, referred_cls, constraint)
 Overriding naming schemes.
Definition at line 79 of file sqla.py.
relation_to_intermediary()
def src.eralchemy.sqla.relation_to_intermediary (fk)
Transform an SQLAlchemy ForeignKey object to it's intermediary representation.
Definition at line 14 of file sqla.py.
References src.eralchemy.sqla.format_name().
Referenced by src.eralchemy.sqla.metadata_to_intermediary().
table_to_intermediary()
def src.eralchemy.sqla.table_to_intermediary (table)
Transform an SQLAlchemy Table object to it's intermediary representation.
Definition at line 56 of file sqla.py.
References src.eralchemy.sqla.column_to_intermediary().
Referenced by src.eralchemy.sqla.metadata_to_intermediary().
Variable Documentation
unicode
src.eralchemy.sqla.unicode = str
Definition at line 11 of file sqla.py.
Referenced by src.eralchemy.sqla.format_name(), and src.eralchemy.sqla.format_type().