ACME: src.utils.backup Namespace Reference
src.utils.backup Namespace Reference
Namespaces
__main__
constant_globals
custom_logger
pathing_defs
Classes
class PoliteDownloader
class JPickleSerializable
Functions
def _get_custom_plain_logger ()
def alias_keys (dict d)
def handle_warning_about_unexpected_exceptions (BaseException be, *Iterable details)
def undo_pickle (fd_or_data, bool is_file=True)
def do_pickle (obj, fd=None, protocol=-1)
List[str] to_list (obj)
Variables
nltk_packages = Path(cache_folder.root).resolve().absolute().joinpath("nltk_packages")
nltk_path_str = str(nltk_packages)
parents
True
exist_ok
download_dir
nltk = None
nltk_loader = None
exc_info
plain_info_logger
txt = PoliteDownloader().list(nltk_path_str, color_coded=True, skip_not_installed=True)
proj_base_info_logger = get_logger("EmailClassifier",__name__+": root logger",level="INFO")
string DB_INTEGER = "INTEGER"
string DB_NULL = "NULL"
string DB_REAL = "REAL"
string DB_TEXT = "TEXT"
string DB_BLOB = "BLOB"
string PROJ_CUSTOM_CLASSES = "COMPLEX_JSON"
string PROJ_SIMPLE_JSON = "SIMPLE_JSON"
dictionary DB_SUPPORTED_TYPES
dictionary DB_PATH_DICT
dictionary TABLE_NAMES
src_warning_logger = get_logger("EmailClassifier",__name__+": warning",level="WARNING")
Function Documentation
_get_custom_plain_logger()
def src.utils.backup._get_custom_plain_logger () private
Definition at line 115 of file __init__.py.
alias_keys()
def src.utils.backup.alias_keys (dict d)
Definition at line 135 of file __init__.py.
do_pickle()
def src.utils.backup.do_pickle (obj, fd = None, protocol = -1)
Definition at line 217 of file __init__.py.
References src.utils.backup.handle_warning_about_unexpected_exceptions().
handle_warning_about_unexpected_exceptions()
def src.utils.backup.handle_warning_about_unexpected_exceptions (BaseException be, *Iterable details)
Definition at line 197 of file __init__.py.
Referenced by src.utils.backup.do_pickle(), and src.utils.backup.undo_pickle().
to_list()
List[str] src.utils.backup.to_list (obj)
Definition at line 251 of file __init__.py.
undo_pickle()
def src.utils.backup.undo_pickle (fd_or_data, bool is_file = True)
Definition at line 203 of file __init__.py.
References src.utils.backup.handle_warning_about_unexpected_exceptions().
Variable Documentation
DB_BLOB
string src.utils.backup.DB_BLOB = "BLOB"
Definition at line 150 of file __init__.py.
DB_INTEGER
string src.utils.backup.DB_INTEGER = "INTEGER"
Definition at line 146 of file __init__.py.
DB_NULL
string src.utils.backup.DB_NULL = "NULL"
Definition at line 147 of file __init__.py.
DB_PATH_DICT
dictionary src.utils.backup.DB_PATH_DICT
Initial value:
 =  {
     "email_cache":cache_folder.joinpath("sql3_email.db"),
     "body_cache":cache_folder.joinpath("sql3_message_body.db"),
     "lemma_cache":cache_folder.joinpath("sql3_extracted_lemma.db"),
     "consolidated_cache":cache_folder.joinpath("sql3_consolidated.db")
 }
Definition at line 179 of file __init__.py.
DB_REAL
string src.utils.backup.DB_REAL = "REAL"
Definition at line 148 of file __init__.py.
DB_SUPPORTED_TYPES
dictionary src.utils.backup.DB_SUPPORTED_TYPES
Initial value:
 =  {
     "int":DB_INTEGER,
     "integer":DB_INTEGER,
     int:DB_INTEGER,
     "None":DB_NULL,
     "NULL":DB_NULL,
     None:DB_NULL,
     "float":DB_REAL,
     "REAL":DB_REAL,
     float:DB_REAL,
     "str":DB_TEXT,
     "TEXT":DB_TEXT,
     str:DB_TEXT,
     "bytes":DB_BLOB,
     "BLOB":DB_BLOB,
     bytes:DB_BLOB,
     "custom_cls":PROJ_CUSTOM_CLASSES,
     PROJ_CUSTOM_CLASSES:PROJ_CUSTOM_CLASSES,
     PROJ_CUSTOM_CLASSES.lower():PROJ_CUSTOM_CLASSES,
     PROJ_SIMPLE_JSON:PROJ_SIMPLE_JSON,
     PROJ_SIMPLE_JSON.lower():PROJ_SIMPLE_JSON,
 }
Definition at line 155 of file __init__.py.
DB_TEXT
string src.utils.backup.DB_TEXT = "TEXT"
Definition at line 149 of file __init__.py.
download_dir
src.utils.backup.download_dir
Definition at line 28 of file __init__.py.
exc_info
src.utils.backup.exc_info
Definition at line 38 of file __init__.py.
exist_ok
src.utils.backup.exist_ok
Definition at line 26 of file __init__.py.
nltk
src.utils.backup.nltk = None
Definition at line 36 of file __init__.py.
nltk_loader
src.utils.backup.nltk_loader = None
Definition at line 37 of file __init__.py.
nltk_packages
src.utils.backup.nltk_packages = Path(cache_folder.root).resolve().absolute().joinpath("nltk_packages")
Definition at line 20 of file __init__.py.
nltk_path_str
src.utils.backup.nltk_path_str = str(nltk_packages)
Definition at line 21 of file __init__.py.
parents
src.utils.backup.parents
Definition at line 26 of file __init__.py.
plain_info_logger
src.utils.backup.plain_info_logger
Initial value:
 =  get_logger("EmailClassifier",__name__+": plain logger",
                                    formatter=_get_custom_plain_logger(),level="INFO")
Definition at line 126 of file __init__.py.
proj_base_info_logger
src.utils.backup.proj_base_info_logger = get_logger("EmailClassifier",__name__+": root logger",level="INFO")
Definition at line 133 of file __init__.py.
PROJ_CUSTOM_CLASSES
string src.utils.backup.PROJ_CUSTOM_CLASSES = "COMPLEX_JSON"
Definition at line 151 of file __init__.py.
PROJ_SIMPLE_JSON
string src.utils.backup.PROJ_SIMPLE_JSON = "SIMPLE_JSON"
Definition at line 152 of file __init__.py.
src_warning_logger
src.utils.backup.src_warning_logger = get_logger("EmailClassifier",__name__+": warning",level="WARNING")
Definition at line 194 of file __init__.py.
TABLE_NAMES
dictionary src.utils.backup.TABLE_NAMES
Initial value:
 =  {
     "email_cache":["emails"],
     "body_cache":["message_body"],
     "lemma_cache":["all_lemma", "no_stopwords_lemma"],
 }
Definition at line 187 of file __init__.py.
True
src.utils.backup.True
Definition at line 26 of file __init__.py.
txt
src.utils.backup.txt = PoliteDownloader().list(nltk_path_str, color_coded=True, skip_not_installed=True)
Definition at line 128 of file __init__.py.