ACME: src.eralchemy.parser Namespace Reference
src.eralchemy.parser Namespace Reference
Classes
class ParsingException
class DuplicateTableException
class DuplicateColumnException
class RelationNoColException
class NoCurrentTableException
class ERAlchemyLineParseError
Functions
def remove_comments_from_line (line)
def _check_no_current_table (new_obj, current_table)
def _update_check_inputs (current_table, tables, relations)
def _check_colname_in_lst (column_name, columns_names)
def _check_not_creating_duplicates (new_name, names, type, exc)
def update_models (new_obj, current_table, tables, relations)
def markdown_file_to_intermediary (filename)
def line_iterator_to_intermediary (line_iterator)
Function Documentation
_check_colname_in_lst()
def src.eralchemy.parser._check_colname_in_lst (column_name, columns_names) private
Definition at line 66 of file parser.py.
Referenced by src.eralchemy.parser.update_models().
_check_no_current_table()
def src.eralchemy.parser._check_no_current_table (new_obj, current_table) private
 Raises exception if we try to add a relation or a column
with no current table.
Definition at line 47 of file parser.py.
Referenced by src.eralchemy.parser.update_models().
_check_not_creating_duplicates()
def src.eralchemy.parser._check_not_creating_duplicates (new_name, names, type, exc) private
Definition at line 72 of file parser.py.
Referenced by src.eralchemy.parser.update_models().
_update_check_inputs()
def src.eralchemy.parser._update_check_inputs (current_table, tables, relations) private
Definition at line 58 of file parser.py.
Referenced by src.eralchemy.parser.update_models().
line_iterator_to_intermediary()
def src.eralchemy.parser.line_iterator_to_intermediary (line_iterator)
 Parse an iterator of str (one string per line) to the intermediary syntax
Definition at line 111 of file parser.py.
References src.eralchemy.parser.remove_comments_from_line(), and src.eralchemy.parser.update_models().
Referenced by src.eralchemy.main.all_to_intermediary(), and src.eralchemy.parser.markdown_file_to_intermediary().
markdown_file_to_intermediary()
def src.eralchemy.parser.markdown_file_to_intermediary (filename)
 Parse a file and return to intermediary syntax.
Definition at line 104 of file parser.py.
References src.eralchemy.parser.line_iterator_to_intermediary().
Referenced by src.eralchemy.main.all_to_intermediary().
remove_comments_from_line()
def src.eralchemy.parser.remove_comments_from_line (line)
Definition at line 41 of file parser.py.
Referenced by src.eralchemy.parser.line_iterator_to_intermediary().
update_models()
def src.eralchemy.parser.update_models (new_obj, current_table, tables, relations)
 Update the state of the parsing.
Definition at line 79 of file parser.py.
References src.eralchemy.parser._check_colname_in_lst(), src.eralchemy.parser._check_no_current_table(), src.eralchemy.parser._check_not_creating_duplicates(), and src.eralchemy.parser._update_check_inputs().
Referenced by src.eralchemy.parser.line_iterator_to_intermediary().